language: c

compiler:
    - gcc

addons:
    apt:
        packages:
            - cmake
            - libldns-dev
            - libunwind8-dev
            - libini-config-dev
            - libatomic-ops-dev

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug .. && make
